FROM python:3.8.3-slim

RUN pip install --upgrade pip

WORKDIR /app

RUN apt-get update && apt-get install -y git
#Imagebind
# RUN apt-get update && apt-get install -y gcc libgeos-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

EXPOSE 8510
# EXPOSE 8511

CMD ["streamlit", "run", "prototype.py", "--server.port", "8510"]
# CMD ["streamlit", "run", "prototype.py", "--server.port", "8511"]