from routers.data_detail import data_detail
from routers.main_chatbot import main_chatbot
from routers.member_chatbot import member_chatbot
from routers.user_convo import user_convo
from routers.user_itinerary import user_itinerary
from routers.user_login import user_login
from routers.refresh_token import refresh_token
from routers.region_autocomplete import region_autocomplete
from routers.STT import STT
from routers.image_upload import image_upload